"""GitHub PR Pipeline — wake-gate + ClaudeCode execution.

Discovers claimable issues, then runs a hard-fail preflight filter:
  - CONTRIBUTING.md AI policy     (reject repos that forbid AI contributions)
  - CLA / DCO requirement         (flag for disclosure / sign-off)
  - Duplicate work                (skip if an open PR already tackles the issue)

Only issues that pass preflight are handed to ClaudeCode via /github-pr.
Working directory: ~/workspace (where repos are forked/cloned)
"""
import subprocess
import json
import os
import re
from datetime import datetime, timezone

WORKSPACE = os.path.expanduser("~/workspace")
CONTRIB_ROOT = os.path.join(WORKSPACE, "contrib")
PR_STAGE_ROOT = os.path.join(WORKSPACE, "pr-stage")
STATUS_FILE = os.path.expanduser("~/.hermes/shared/.last-github-pr")
POLICY_CACHE = os.path.expanduser("~/.hermes/shared/policy-cache.json")

LANGUAGES = ["python", "rust", "go", "javascript", "typescript"]
AUTHOR = "CrepuscularIRIS"

# Phrases that indicate a repo REJECTS AI-generated contributions.
# Must co-occur with a prohibition verb in the same sentence.
AI_MARKERS = [
    "ai generated", "ai-generated", "ai content",
    "ai assistant", "ai-assistant", "ai assisted",
    "ai tool", "generative ai", "generated by ai",
    "llm generated", "llm-generated", "chatgpt", "copilot",
    "large language model",
]
PROHIBIT_MARKERS = [
    "forbidden", "forbid", "prohibited", "prohibit",
    "not allowed", "not permitted", "no ai",
    "will be rejected", "will be closed", "do not submit",
    "please do not", "reject", "banned", "disallow",
    "refuse", "unacceptable",
]

CLA_MARKERS = [
    "contributor license agreement", "sign the cla", "cla bot",
    "cla-assistant", "cla signed", "sign our cla",
    "developer certificate of origin", "dco", "signed-off-by",
    "sign-off", "sign off your commit",
]


def get_claimable_issues():
    all_issues = []
    labels = ["good first issue", "help wanted", "bug"]
    for lang in LANGUAGES:
        for label in labels:
            result = subprocess.run(
                ["gh", "search", "issues",
                 f"--label={label}",
                 "--state=open", "--sort=updated",
                 f"--language={lang}", "--limit=2",
                 "--json=number,title,repository,labels"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode != 0:
                continue
            try:
                issues = json.loads(result.stdout) or []
                all_issues.extend(issues)
            except json.JSONDecodeError:
                continue

    seen = set()
    deduped = []
    for issue in all_issues:
        key = f"{issue['repository']['nameWithOwner']}#{issue['number']}"
        if key not in seen:
            seen.add(key)
            deduped.append(issue)
    return deduped


def load_policy_cache():
    if not os.path.exists(POLICY_CACHE):
        return {}
    try:
        with open(POLICY_CACHE) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def save_policy_cache(cache):
    os.makedirs(os.path.dirname(POLICY_CACHE), exist_ok=True)
    with open(POLICY_CACHE, "w") as f:
        json.dump(cache, f, indent=2)


def fetch_repo_file(repo, path):
    """Read a file from the default branch via gh api. Returns text or None."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/contents/{path}",
             "--jq", ".content"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0 or not result.stdout.strip():
            return None
        import base64
        raw = base64.b64decode(result.stdout.strip()).decode("utf-8", errors="ignore")
        return raw
    except (subprocess.TimeoutExpired, ValueError, OSError):
        return None


def scan_ai_policy(text):
    """Return (forbids_ai, evidence_snippet) for a CONTRIBUTING/README text."""
    if not text:
        return False, ""
    lowered = text.lower()
    # Split into rough sentences and hunt for AI-marker + prohibit-marker in same chunk
    chunks = re.split(r"(?<=[.!?\n])\s+", lowered)
    for chunk in chunks:
        if any(m in chunk for m in AI_MARKERS) and any(p in chunk for p in PROHIBIT_MARKERS):
            return True, chunk.strip()[:240]
    return False, ""


def scan_cla_required(text):
    if not text:
        return False, ""
    lowered = text.lower()
    for marker in CLA_MARKERS:
        if marker in lowered:
            idx = lowered.find(marker)
            snippet = lowered[max(0, idx - 60):idx + 180].strip()
            return True, snippet[:240]
    return False, ""


def scan_closed_prs_for_ai_rejection(repo):
    """Some repos (e.g. secureblue) hide their AI policy on an external site.
    If recently-closed-unmerged PRs show AI-rejection language, treat as forbidden.
    """
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--state", "closed",
             "--limit", "30",
             "--json", "number,mergedAt,closedAt,comments"],
            capture_output=True, text=True, timeout=20
        )
        if result.returncode != 0:
            return False, ""
        prs = json.loads(result.stdout or "[]")
        for pr in prs:
            if pr.get("mergedAt"):
                continue
            for comment in (pr.get("comments") or []):
                body = (comment.get("body") or "").lower()
                if "ai content" in body or "ai-content" in body or "ai generated" in body or "ai-generated" in body:
                    if any(p in body for p in ["forbid", "policy", "not accept", "not permit", "prohibit", "reject"]):
                        return True, body[:200]
        return False, ""
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return False, ""


def check_repo_policy(repo, cache):
    """Return dict: {forbids_ai, ai_evidence, needs_cla, cla_evidence, has_contributing}."""
    if repo in cache:
        return cache[repo]

    contributing = (
        fetch_repo_file(repo, "CONTRIBUTING.md")
        or fetch_repo_file(repo, "CONTRIBUTING.rst")
        or fetch_repo_file(repo, ".github/CONTRIBUTING.md")
        or fetch_repo_file(repo, "docs/CONTRIBUTING.md")
        or ""
    )
    readme = fetch_repo_file(repo, "README.md") or ""
    combined = contributing + "\n" + readme

    forbids_ai, ai_ev = scan_ai_policy(combined)
    needs_cla, cla_ev = scan_cla_required(combined)

    # Secondary: check closed-PR rejection history for off-repo policies
    if not forbids_ai:
        forbids_ai, ai_ev = scan_closed_prs_for_ai_rejection(repo)
        if forbids_ai:
            ai_ev = f"[from closed-PR history] {ai_ev}"

    result = {
        "forbids_ai": forbids_ai,
        "ai_evidence": ai_ev,
        "needs_cla": needs_cla,
        "cla_evidence": cla_ev,
        "has_contributing": bool(contributing),
        "checked_at": datetime.now(timezone.utc).isoformat(),
    }
    cache[repo] = result
    return result


def has_duplicate_pr(repo, issue_number):
    """True if an open PR already references this issue via Fixes/Closes/Resolves."""
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--state", "open",
             "--search", f"#{issue_number}",
             "--json", "number,title,author,body"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0:
            return False
        prs = json.loads(result.stdout or "[]")
        keyword_re = re.compile(
            rf"\b(fixes|closes|resolves)\s+#{issue_number}\b",
            re.IGNORECASE,
        )
        for pr in prs:
            if keyword_re.search(pr.get("body") or "") or f"#{issue_number}" in (pr.get("title") or ""):
                return True
        return False
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return False


def has_existing_claim(repo, issue_number):
    """True if someone else already commented 'I'll work on this' or similar."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/issues/{issue_number}/comments",
             "--jq", "[.[] | {login: .user.login, body: .body}]"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0:
            return False
        comments = json.loads(result.stdout or "[]")
        claim_patterns = [
            r"\bi.{0,3}ll (take|work on|pick.{0,3}up|handle)",
            r"\bi.{0,3}m working on",
            r"\bworking on (this|it)\b",
            r"\b/assign\b",
            r"\bcan i (take|work on)",
        ]
        for c in comments:
            login = c.get("login", "")
            if login == AUTHOR:
                continue
            body = (c.get("body") or "").lower()
            for pat in claim_patterns:
                if re.search(pat, body):
                    return True
        return False
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return False


def preflight_filter(issues):
    """Return (approved, rejected) tuples with reasons."""
    cache = load_policy_cache()
    approved = []
    rejected = []

    for issue in issues:
        repo = issue["repository"]["nameWithOwner"]
        number = issue["number"]
        key = f"{repo}#{number}"

        policy = check_repo_policy(repo, cache)

        if policy["forbids_ai"]:
            rejected.append((issue, f"AI-forbidden repo. Evidence: {policy['ai_evidence']}"))
            continue

        if has_duplicate_pr(repo, number):
            rejected.append((issue, f"Open PR already references #{number}"))
            continue

        if has_existing_claim(repo, number):
            rejected.append((issue, f"Another contributor already claimed #{number}"))
            continue

        issue["_policy"] = policy
        approved.append(issue)

    save_policy_cache(cache)
    return approved, rejected


def extract_pr_url(text):
    match = re.search(r'https://github\.com/[^\s)]+/pull/\d+', text)
    return match.group(0) if match else None


def write_status(status, detail=""):
    os.makedirs(os.path.dirname(STATUS_FILE), exist_ok=True)
    ts = datetime.now(timezone.utc).isoformat()
    with open(STATUS_FILE, "w") as f:
        json.dump({"status": status, "detail": detail, "timestamp": ts}, f)


def main():
    os.makedirs(WORKSPACE, exist_ok=True)
    os.makedirs(CONTRIB_ROOT, exist_ok=True)
    os.makedirs(PR_STAGE_ROOT, exist_ok=True)

    raw_issues = get_claimable_issues()
    if not raw_issues:
        write_status("no-issues-found")
        print(json.dumps({"wakeAgent": False}))
        return

    approved, rejected = preflight_filter(raw_issues[:12])
    approved = approved[:5]

    if rejected:
        print("Preflight rejections:")
        for issue, reason in rejected:
            repo = issue["repository"]["nameWithOwner"]
            print(f"  - {repo}#{issue['number']}: {reason}")

    if not approved:
        detail = f"{len(rejected)} rejected in preflight, 0 approved"
        write_status("no-approved-issues", detail)
        print(json.dumps({"wakeAgent": False}))
        return

    issue_lines = []
    for issue in approved:
        repo = issue["repository"]["nameWithOwner"]
        pol = issue.get("_policy", {})
        flags = []
        if pol.get("needs_cla"):
            flags.append("CLA-REQUIRED")
        if not pol.get("has_contributing"):
            flags.append("NO-CONTRIBUTING")
        flag_str = f" [{', '.join(flags)}]" if flags else ""
        issue_lines.append(
            f"- {repo}#{issue['number']}: {issue['title']}{flag_str}"
        )
    issue_list = "\n".join(issue_lines)

    prompt = (
        f"/github-pr\n\n"
        f"Candidate issues (preflight-approved):\n\n"
        f"{issue_list}\n\n"
        f"Routing anchors (must follow exactly):\n"
        f"- Workspace root: {WORKSPACE}\n"
        f"- Contribution repos: {CONTRIB_ROOT}/<repo-name>/\n"
        f"- Planning-with-Files root: {PR_STAGE_ROOT}/<repo-name>/\n"
        f"- Required files: task_plan.md, findings.md, progress.md\n"
        f"- PR report: {PR_STAGE_ROOT}/<repo-name>/pr-report.md\n"
        f"- Superpowers plans (repo-local): <repo-root>/docs/superpowers/plans/\n\n"
        f"HARD-FAIL GATES (abort the issue if any trigger):\n"
        f"1. Open and READ the repo's CONTRIBUTING.md before writing code. If it forbids AI\n"
        f"   assistance in any form (e.g. 'no AI-generated code', 'LLM output prohibited'),\n"
        f"   skip this issue and log a 'repo-forbids-ai' rejection. Do NOT submit anyway.\n"
        f"2. If the issue flag shows CLA-REQUIRED, verify the CLA bot and sign the CLA BEFORE\n"
        f"   pushing. If you cannot sign (manual step), skip the issue and log 'cla-blocked'.\n"
        f"3. Re-check for duplicate PRs right before `gh pr create`. If someone opened a PR\n"
        f"   since preflight, close yours with a courteous note yielding to theirs.\n\n"
        f"REPLY / PR-BODY TONE (non-negotiable):\n"
        f"- Humility over cleverness. Use phrases like 'I might be wrong, but...',\n"
        f"  'If this direction doesn't fit, no problem.'\n"
        f"- Never mention internal tooling: no agent names, no multi-model pipelines,\n"
        f"  no orchestration systems, no 'my analysis shows'.\n"
        f"- Match the project's language (terminology, style, commit format) exactly.\n"
        f"- Include the AI Disclosure line per PullRequest.md: a short factual note that\n"
        f"  AI tools assisted, manually reviewed and tested.\n"
        f"- No status tables, no bolded usernames, no emoji-headed sections.\n\n"
        f"Before implementation, ensure planning files exist in pr-stage for the selected repo.\n"
        f"Use codex:codex-rescue for implementation.\n"
        f"Use gemini:gemini-consult for architecture checks. If Gemini startup is slow, allow warm-up and retry once.\n"
        f"Pick the most suitable issue and execute the full pipeline.\n\n"
        f"IMPORTANT: At the end of your work, print a summary line in this exact format:\n"
        f"PIPELINE_RESULT: <status> | <pr_url_or_reason>\n"
        f"Where status is one of: pr-created, pr-failed, issue-skipped, repo-forbids-ai, cla-blocked, duplicate, error\n"
        f"Example: PIPELINE_RESULT: pr-created | https://github.com/org/repo/pull/123"
    )

    result = subprocess.run(
        ["claude", "-p", "--model", "sonnet",
         "--dangerously-skip-permissions",
         "--max-budget-usd", "5.00",
         prompt],
        capture_output=True, text=True,
        timeout=7200,
        cwd=WORKSPACE
    )

    stdout = result.stdout.strip()
    stderr = result.stderr.strip()

    if result.returncode != 0:
        detail = stderr[:500] if stderr else "unknown error"
        write_status("error", f"exit {result.returncode}: {detail}")
        print(f"PIPELINE_ERROR: ClaudeCode exited {result.returncode}\n{detail}")
        return

    if not stdout:
        write_status("empty-output", f"exit 0 but no stdout. stderr: {stderr[:200]}")
        print(f"PIPELINE_ERROR: ClaudeCode exited 0 but produced no output.")
        if stderr:
            print(f"stderr: {stderr[:1000]}")
        print(f"\nCandidate issues were:\n{issue_list}")
        return

    pr_url = extract_pr_url(stdout)
    pipeline_match = re.search(r'PIPELINE_RESULT:\s*(\S+)\s*\|\s*(.*)', stdout)

    if pipeline_match:
        status = pipeline_match.group(1).strip()
        detail = pipeline_match.group(2).strip()
        write_status(status, detail)
    elif pr_url:
        write_status("pr-created", pr_url)
    else:
        write_status("completed-no-pr", stdout[-200:])

    print(stdout[-4000:] if len(stdout) > 4000 else stdout)


if __name__ == "__main__":
    main()
