"""GitHub PR Pipeline — wake-gate + ClaudeCode execution.

Discovers claimable issues, then runs a hard-fail preflight filter:
  - CONTRIBUTING.md AI policy     (reject repos that forbid AI contributions)
  - CLA / DCO requirement         (flag for disclosure / sign-off)
  - Duplicate work                (skip if an open PR already tackles the issue)

Only issues that pass preflight are handed to ClaudeCode via /github-pr.
Working directory: ~/workspace (where repos are forked/cloned)
"""
import subprocess
import json
import os
import re
from datetime import datetime, timezone

WORKSPACE = os.path.expanduser("~/workspace")
CONTRIB_ROOT = os.path.join(WORKSPACE, "contrib")
PR_STAGE_ROOT = os.path.join(WORKSPACE, "pr-stage")
STATUS_FILE = os.path.expanduser("~/.hermes/shared/.last-github-pr")
POLICY_CACHE = os.path.expanduser("~/.hermes/shared/policy-cache.json")

LANGUAGES = ["python", "rust", "go", "javascript", "typescript"]
AUTHOR = "CrepuscularIRIS"

# Phrases that indicate a repo REJECTS AI-generated contributions.
# Must co-occur with a prohibition verb in the same sentence.
AI_MARKERS = [
    "ai generated", "ai-generated", "ai content",
    "ai assistant", "ai-assistant", "ai assisted",
    "ai tool", "generative ai", "generated by ai",
    "llm generated", "llm-generated", "chatgpt", "copilot",
    "large language model",
]
PROHIBIT_MARKERS = [
    "forbidden", "forbid", "prohibited", "prohibit",
    "not allowed", "not permitted", "no ai",
    "will be rejected", "will be closed", "do not submit",
    "please do not", "reject", "banned", "disallow",
    "refuse", "unacceptable",
]

CLA_MARKERS = [
    "contributor license agreement", "sign the cla", "cla bot",
    "cla-assistant", "cla signed", "sign our cla",
    "developer certificate of origin", "dco", "signed-off-by",
    "sign-off", "sign off your commit",
]


def get_claimable_issues():
    all_issues = []
    labels = ["good first issue", "help wanted", "bug"]
    for lang in LANGUAGES:
        for label in labels:
            result = subprocess.run(
                ["gh", "search", "issues",
                 f"--label={label}",
                 "--state=open", "--sort=updated",
                 f"--language={lang}", "--limit=2",
                 "--json=number,title,repository,labels"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode != 0:
                continue
            try:
                issues = json.loads(result.stdout) or []
                all_issues.extend(issues)
            except json.JSONDecodeError:
                continue

    seen = set()
    deduped = []
    for issue in all_issues:
        key = f"{issue['repository']['nameWithOwner']}#{issue['number']}"
        if key not in seen:
            seen.add(key)
            deduped.append(issue)
    return deduped


def load_policy_cache():
    if not os.path.exists(POLICY_CACHE):
        return {}
    try:
        with open(POLICY_CACHE) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def save_policy_cache(cache):
    os.makedirs(os.path.dirname(POLICY_CACHE), exist_ok=True)
    with open(POLICY_CACHE, "w") as f:
        json.dump(cache, f, indent=2)


def fetch_repo_file(repo, path):
    """Read a file from the default branch via gh api. Returns text or None."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/contents/{path}",
             "--jq", ".content"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0 or not result.stdout.strip():
            return None
        import base64
        raw = base64.b64decode(result.stdout.strip()).decode("utf-8", errors="ignore")
        return raw
    except (subprocess.TimeoutExpired, ValueError, OSError):
        return None


def scan_ai_policy(text):
    """Return (forbids_ai, evidence_snippet) for a CONTRIBUTING/README text."""
    if not text:
        return False, ""
    lowered = text.lower()
    # Split into rough sentences and hunt for AI-marker + prohibit-marker in same chunk
    chunks = re.split(r"(?<=[.!?\n])\s+", lowered)
    for chunk in chunks:
        if any(m in chunk for m in AI_MARKERS) and any(p in chunk for p in PROHIBIT_MARKERS):
            return True, chunk.strip()[:240]
    return False, ""


def scan_cla_required(text):
    if not text:
        return False, ""
    lowered = text.lower()
    for marker in CLA_MARKERS:
        if marker in lowered:
            idx = lowered.find(marker)
            snippet = lowered[max(0, idx - 60):idx + 180].strip()
            return True, snippet[:240]
    return False, ""


def scan_closed_prs_for_ai_rejection(repo):
    """Some repos (e.g. secureblue) hide their AI policy on an external site.
    If recently-closed-unmerged PRs show AI-rejection language, treat as forbidden.
    """
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--state", "closed",
             "--limit", "30",
             "--json", "number,mergedAt,closedAt,comments"],
            capture_output=True, text=True, timeout=20
        )
        if result.returncode != 0:
            return False, ""
        prs = json.loads(result.stdout or "[]")
        for pr in prs:
            if pr.get("mergedAt"):
                continue
            for comment in (pr.get("comments") or []):
                body = (comment.get("body") or "").lower()
                if "ai content" in body or "ai-content" in body or "ai generated" in body or "ai-generated" in body:
                    if any(p in body for p in ["forbid", "policy", "not accept", "not permit", "prohibit", "reject"]):
                        return True, body[:200]
        return False, ""
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return False, ""


def check_repo_policy(repo, cache):
    """Return dict: {forbids_ai, ai_evidence, needs_cla, cla_evidence, has_contributing}."""
    if repo in cache:
        return cache[repo]

    contributing = (
        fetch_repo_file(repo, "CONTRIBUTING.md")
        or fetch_repo_file(repo, "CONTRIBUTING.rst")
        or fetch_repo_file(repo, ".github/CONTRIBUTING.md")
        or fetch_repo_file(repo, "docs/CONTRIBUTING.md")
        or ""
    )
    readme = fetch_repo_file(repo, "README.md") or ""
    combined = contributing + "\n" + readme

    forbids_ai, ai_ev = scan_ai_policy(combined)
    needs_cla, cla_ev = scan_cla_required(combined)

    # Secondary: check closed-PR rejection history for off-repo policies
    if not forbids_ai:
        forbids_ai, ai_ev = scan_closed_prs_for_ai_rejection(repo)
        if forbids_ai:
            ai_ev = f"[from closed-PR history] {ai_ev}"

    result = {
        "forbids_ai": forbids_ai,
        "ai_evidence": ai_ev,
        "needs_cla": needs_cla,
        "cla_evidence": cla_ev,
        "has_contributing": bool(contributing),
        "checked_at": datetime.now(timezone.utc).isoformat(),
    }
    cache[repo] = result
    return result


def has_duplicate_pr(repo, issue_number):
    """True if an open PR already references this issue via Fixes/Closes/Resolves."""
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--state", "open",
             "--search", f"#{issue_number}",
             "--json", "number,title,author,body"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0:
            return False
        prs = json.loads(result.stdout or "[]")
        keyword_re = re.compile(
            rf"\b(fixes|closes|resolves)\s+#{issue_number}\b",
            re.IGNORECASE,
        )
        for pr in prs:
            if keyword_re.search(pr.get("body") or "") or f"#{issue_number}" in (pr.get("title") or ""):
                return True
        return False
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return False


def _fetch_issue_comments(repo, issue_number):
    """Return list of {login, body, author_association} dicts, or []."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/issues/{issue_number}/comments",
             "--jq", "[.[] | {login: .user.login, body: .body, author_association: .author_association}]"],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode != 0:
            return []
        return json.loads(result.stdout or "[]")
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return []


# Labels that block contribution — DETERMINISTIC match, stays in Python.
# For dispute / AI-policy / claim interpretation, see pr-direction-check skill.
BLOCK_LABELS = {
    "wontfix", "won't fix", "wont fix",
    "invalid", "duplicate",
    "needs-design", "needs design", "design needed",
    "needs-discussion", "needs discussion",
    "blocked", "on hold", "on-hold",
    "status: blocked", "status: on-hold",
    "question", "stale",
}


def has_block_label(issue):
    """True if issue carries a label that blocks contribution (wontfix, invalid, etc.).

    Deterministic label string match. Judgment calls (dispute detection,
    stale-but-still-valid) are deferred to pr-direction-check skill.
    """
    for lbl in issue.get("labels", []):
        name = (lbl.get("name") if isinstance(lbl, dict) else str(lbl)).strip().lower()
        if name in BLOCK_LABELS:
            return True, name
    return False, ""


def preflight_filter(issues):
    """Return (approved, rejected) tuples with reasons.

    ONLY DETERMINISTIC GATES run here. Judgment calls (dispute detection,
    AI-policy interpretation, claim-recency reading) are deferred to the
    pr-direction-check skill, invoked downstream by /github-pr Phase 2.5.

    Deterministic gates, in order:
      1. Issue has block-label (wontfix / invalid / needs-design / etc.)
      2. Duplicate open PR already references this issue (Fixes/Closes/Resolves #N)
      3. Contributing.md exists check (info only — the skill will READ it)

    Passing preflight means the issue is worth spending the claude -p session
    on; the session itself runs pr-direction-check for the nuanced verdict.
    """
    cache = load_policy_cache()
    approved = []
    rejected = []

    for issue in issues:
        repo = issue["repository"]["nameWithOwner"]
        number = issue["number"]

        # Gate 1: block-label — deterministic
        blocked, lbl = has_block_label(issue)
        if blocked:
            rejected.append((issue, f"Issue has block-label '{lbl}'"))
            continue

        # Gate 2: duplicate open PR — deterministic `Fixes #N` grep
        if has_duplicate_pr(repo, number):
            rejected.append((issue, f"Open PR already references #{number}"))
            continue

        # Gather the data the skill will judge — but don't judge here.
        # Cache fetched data on the issue so the prompt can pass it along.
        policy = check_repo_policy(repo, cache)  # fetches CONTRIBUTING.md text
        comments = _fetch_issue_comments(repo, number)
        issue["_policy"] = policy
        issue["_comments"] = comments[-20:]  # last 20 for the skill
        approved.append(issue)

    save_policy_cache(cache)
    return approved, rejected


def extract_pr_url(text):
    match = re.search(r'https://github\.com/[^\s)]+/pull/\d+', text)
    return match.group(0) if match else None


def write_status(status, detail="", extra=None):
    os.makedirs(os.path.dirname(STATUS_FILE), exist_ok=True)
    ts = datetime.now(timezone.utc).isoformat()
    payload = {"status": status, "detail": detail, "timestamp": ts}
    if extra:
        payload.update(extra)
    with open(STATUS_FILE, "w") as f:
        json.dump(payload, f)


def main():
    os.makedirs(WORKSPACE, exist_ok=True)
    os.makedirs(CONTRIB_ROOT, exist_ok=True)
    os.makedirs(PR_STAGE_ROOT, exist_ok=True)

    raw_issues = get_claimable_issues()
    if not raw_issues:
        write_status("no-issues-found")
        print(json.dumps({"wakeAgent": False}))
        return

    approved, rejected = preflight_filter(raw_issues[:12])
    approved = approved[:5]

    if rejected:
        print("Preflight rejections:")
        for issue, reason in rejected:
            repo = issue["repository"]["nameWithOwner"]
            print(f"  - {repo}#{issue['number']}: {reason}")

    if not approved:
        detail = f"{len(rejected)} rejected in preflight, 0 approved"
        write_status("no-approved-issues", detail)
        print(json.dumps({"wakeAgent": False}))
        return

    issue_lines = []
    for issue in approved:
        repo = issue["repository"]["nameWithOwner"]
        pol = issue.get("_policy", {})
        flags = []
        if pol.get("needs_cla"):
            flags.append("CLA-REQUIRED")
        if not pol.get("has_contributing"):
            flags.append("NO-CONTRIBUTING")
        flag_str = f" [{', '.join(flags)}]" if flags else ""
        issue_lines.append(
            f"- {repo}#{issue['number']}: {issue['title']}{flag_str}"
        )
    issue_list = "\n".join(issue_lines)

    # Build the direction-check input blob for each candidate — the skill
    # reads this to make the judgment call Python can't reliably make.
    issue_blobs = []
    for issue in approved:
        pol = issue.get("_policy", {})
        comments = issue.get("_comments", [])
        blob = {
            "repo": issue["repository"]["nameWithOwner"],
            "issue_number": issue["number"],
            "issue_title": issue.get("title", ""),
            "labels": [(l.get("name") if isinstance(l, dict) else str(l))
                       for l in issue.get("labels", [])],
            "last_comments": [
                {"author": c.get("login"),
                 "role": c.get("author_association"),
                 "body": (c.get("body") or "")[:1500]}
                for c in comments
            ],
            "contributing_md_present": pol.get("has_contributing", False),
            "needs_cla_signal": pol.get("needs_cla", False),
        }
        issue_blobs.append(blob)

    direction_blob_json = json.dumps(issue_blobs, ensure_ascii=False, indent=2)[:8000]

    prompt = (
        f"/github-pr\n\n"
        f"Candidate issues (preflight-approved — block-label + duplicate-PR gates passed):\n\n"
        f"{issue_list}\n\n"
        f"DIRECTION-CHECK INPUT (judgment data — consume via pr-direction-check skill):\n"
        f"```json\n{direction_blob_json}\n```\n\n"
        f"Routing anchors (must follow exactly):\n"
        f"- Workspace root: {WORKSPACE}\n"
        f"- Contribution repos: {CONTRIB_ROOT}/<repo-name>/\n"
        f"- Planning-with-Files root: {PR_STAGE_ROOT}/<repo-name>/\n"
        f"- Required files: task_plan.md, findings.md, progress.md\n"
        f"- PR report: {PR_STAGE_ROOT}/<repo-name>/pr-report.md\n\n"
        f"MANDATORY FIRST STEP — Phase 2.5 direction check:\n"
        f"For each candidate, invoke Skill(\"pr-direction-check\") with the matching\n"
        f"blob above. The skill returns DIRECTION_VERDICT: <status> | <reason>.\n"
        f"- proceed → continue to clone + code\n"
        f"- block:* → emit PIPELINE_RESULT with the matching status, skip this candidate\n"
        f"- yield:* → emit PIPELINE_RESULT: duplicate | <reason>, skip\n"
        f"- ambiguous:* → STOP, emit PIPELINE_RESULT: needs-human | <reason>, do NOT\n"
        f"  submit anything. Surface the ambiguity in the final report so a human decides.\n\n"
        f"FINAL-SUBMISSION GATES (re-check right before `gh pr create`):\n"
        f"1. Duplicate check — a PR may have opened in the last hour; if so, close your\n"
        f"   branch with a polite yield.\n"
        f"2. If CLA required and unsigned: emit PIPELINE_RESULT: cla-blocked.\n\n"
        f"REPLY / PR-BODY TONE (non-negotiable):\n"
        f"- Humility over cleverness. Use 'I might be wrong, but...',\n"
        f"  'If this direction doesn't fit, no problem.'\n"
        f"- No internal tooling references (agent names, orchestration, 'my analysis shows').\n"
        f"- Match the project's language. AI disclosure per PullRequest.md §AI Disclosure.\n"
        f"- No status tables, no bolded usernames, no emoji-headed sections.\n\n"
        f"Use codex:codex-rescue for implementation; gemini:gemini-consult for architecture.\n"
        f"Pick the most suitable proceed-verdict candidate and execute the full pipeline.\n\n"
        f"IMPORTANT: At the end, print in this exact format:\n"
        f"PIPELINE_RESULT: <status> | <pr_url_or_reason>\n"
        f"PIPELINE_QUALITY_SCORE: <float 0-10>   # mean of triple-review; required when status=pr-created\n\n"
        f"Status values: pr-created, pr-failed, issue-skipped, needs-human,\n"
        f"repo-forbids-ai, cla-blocked, duplicate, maintainer-disputed, error"
    )

    result = subprocess.run(
        ["claude", "-p", "--model", "sonnet",
         "--dangerously-skip-permissions",
         "--max-budget-usd", "5.00",
         prompt],
        capture_output=True, text=True,
        timeout=7200,
        cwd=WORKSPACE
    )

    stdout = result.stdout.strip()
    stderr = result.stderr.strip()

    if result.returncode != 0:
        detail = stderr[:500] if stderr else "unknown error"
        write_status("error", f"exit {result.returncode}: {detail}")
        print(f"PIPELINE_ERROR: ClaudeCode exited {result.returncode}\n{detail}")
        return

    if not stdout:
        write_status("empty-output", f"exit 0 but no stdout. stderr: {stderr[:200]}")
        print(f"PIPELINE_ERROR: ClaudeCode exited 0 but produced no output.")
        if stderr:
            print(f"stderr: {stderr[:1000]}")
        print(f"\nCandidate issues were:\n{issue_list}")
        return

    pr_url = extract_pr_url(stdout)
    pipeline_match = re.search(r'PIPELINE_RESULT:\s*(\S+)\s*\|\s*(.*)', stdout)
    score_match = re.search(r'PIPELINE_QUALITY_SCORE:\s*([0-9]+(?:\.[0-9]+)?)', stdout)
    score = float(score_match.group(1)) if score_match else None

    QUALITY_THRESHOLD = 7.0

    if pipeline_match:
        status = pipeline_match.group(1).strip()
        detail = pipeline_match.group(2).strip()

        # Quality-score enforcement: if status claims pr-created, require a
        # score ≥ threshold. Block the "success" classification otherwise.
        if status == "pr-created":
            if score is None:
                status = "pr-created-unscored"
                detail = f"SCORE MISSING — original detail: {detail}"
            elif score < QUALITY_THRESHOLD:
                status = "quality-blocked"
                detail = f"score={score} < {QUALITY_THRESHOLD} — original: {detail}"
            else:
                detail = f"{detail}  [quality={score}]"
        extra = {"quality_score": score} if score is not None else {}
        write_status(status, detail, extra=extra)
    elif pr_url:
        if score is None or score < QUALITY_THRESHOLD:
            write_status("pr-created-unscored" if score is None else "quality-blocked",
                         pr_url, extra={"quality_score": score} if score is not None else {})
        else:
            write_status("pr-created", pr_url, extra={"quality_score": score})
    else:
        write_status("completed-no-pr", stdout[-200:])

    print(stdout[-4000:] if len(stdout) > 4000 else stdout)


if __name__ == "__main__":
    main()
