"""GitHub PR Pipeline — wake-gate + ClaudeCode execution.

Discovers claimable issues, then runs a hard-fail preflight filter:
  - CONTRIBUTING.md AI policy     (reject repos that forbid AI contributions)
  - CLA / DCO requirement         (flag for disclosure / sign-off)
  - Duplicate work                (skip if an open PR already tackles the issue)

Only issues that pass preflight are handed to ClaudeCode via /github-pr.
Working directory: ~/workspace (where repos are forked/cloned)
"""
import subprocess
import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone

from beatless_config import CONFIG

WORKSPACE = str(CONFIG.workspace)
CONTRIB_ROOT = str(CONFIG.contrib_root)
PR_STAGE_ROOT = str(CONFIG.pr_stage_root)
STATUS_FILE = str(CONFIG.shared_file(".last-github-pr"))
POLICY_CACHE = str(CONFIG.shared_file("policy-cache.json"))

LANGUAGES = ["python", "rust", "go", "javascript", "typescript"]
AUTHOR = CONFIG.github_author


def log(message):
    print(f"[github-pr] {message}", file=sys.stderr, flush=True)


def gh_auth_status():
    try:
        return subprocess.run(
            ["gh", "auth", "status"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return subprocess.CompletedProcess(
            ["gh", "auth", "status"],
            returncode=1,
            stdout="",
            stderr=str(exc),
        )

# Phrases that indicate a repo REJECTS AI-generated contributions.
# Must co-occur with a prohibition verb in the same sentence.
AI_MARKERS = [
    "ai generated", "ai-generated", "ai content",
    "ai assistant", "ai-assistant", "ai assisted",
    "ai tool", "generative ai", "generated by ai",
    "llm generated", "llm-generated", "chatgpt", "copilot",
    "large language model",
]
PROHIBIT_MARKERS = [
    "forbidden", "forbid", "prohibited", "prohibit",
    "not allowed", "not permitted", "no ai",
    "will be rejected", "will be closed", "do not submit",
    "please do not", "reject", "banned", "disallow",
    "refuse", "unacceptable",
]

CLA_MARKERS = [
    "contributor license agreement", "sign the cla", "cla bot",
    "cla-assistant", "cla signed", "sign our cla",
    "developer certificate of origin", "dco", "signed-off-by",
    "sign-off", "sign off your commit",
]


def get_claimable_issues(languages=None, labels=None, per_query_limit=2):
    all_issues = []
    languages = languages or LANGUAGES
    labels = labels or ["good first issue", "help wanted", "bug"]
    per_query_limit = max(1, int(per_query_limit))
    total_queries = len(languages) * len(labels)
    query_index = 0
    for lang in languages:
        for label in labels:
            query_index += 1
            log(f"discover {query_index}/{total_queries}: language={lang} label={label!r}")
            result = subprocess.run(
                ["gh", "search", "issues",
                 f"--label={label}",
                 "--state=open", "--sort=updated",
                 f"--language={lang}", f"--limit={per_query_limit}",
                 "--json=number,title,repository,labels"],
                capture_output=True, text=True, timeout=30
            )
            if result.returncode != 0:
                tail = (result.stderr or result.stdout or "").strip()[-240:]
                log(f"discover skipped: language={lang} label={label!r} gh exited {result.returncode}: {tail}")
                continue
            try:
                issues = json.loads(result.stdout) or []
                log(f"discover found {len(issues)} issue(s): language={lang} label={label!r}")
                all_issues.extend(issues)
            except json.JSONDecodeError:
                log(f"discover skipped: language={lang} label={label!r} returned invalid JSON")
                continue

    seen = set()
    deduped = []
    for issue in all_issues:
        key = f"{issue['repository']['nameWithOwner']}#{issue['number']}"
        if key not in seen:
            seen.add(key)
            deduped.append(issue)
    return deduped


def load_policy_cache():
    if not os.path.exists(POLICY_CACHE):
        return {}
    try:
        with open(POLICY_CACHE) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def save_policy_cache(cache):
    os.makedirs(os.path.dirname(POLICY_CACHE), exist_ok=True)
    with open(POLICY_CACHE, "w") as f:
        json.dump(cache, f, indent=2)


def fetch_repo_file(repo, path):
    """Read a file from the default branch via gh api. Returns text or None."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/contents/{path}",
             "--jq", ".content"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0 or not result.stdout.strip():
            return None
        import base64
        raw = base64.b64decode(result.stdout.strip()).decode("utf-8", errors="ignore")
        return raw
    except (subprocess.TimeoutExpired, ValueError, OSError):
        return None


def scan_ai_policy(text):
    """Return (forbids_ai, evidence_snippet) for a CONTRIBUTING/README text."""
    if not text:
        return False, ""
    lowered = text.lower()
    # Split into rough sentences and hunt for AI-marker + prohibit-marker in same chunk
    chunks = re.split(r"(?<=[.!?\n])\s+", lowered)
    for chunk in chunks:
        if any(m in chunk for m in AI_MARKERS) and any(p in chunk for p in PROHIBIT_MARKERS):
            return True, chunk.strip()[:240]
    return False, ""


def scan_cla_required(text):
    if not text:
        return False, ""
    lowered = text.lower()
    for marker in CLA_MARKERS:
        marker_re = re.compile(rf"(?<![a-z0-9]){re.escape(marker)}(?![a-z0-9])")
        match = marker_re.search(lowered)
        if match:
            idx = match.start()
            snippet = lowered[max(0, idx - 60):idx + 180].strip()
            return True, snippet[:240]
    return False, ""


def scan_closed_prs_for_ai_rejection(repo):
    """Some repos (e.g. secureblue) hide their AI policy on an external site.
    If recently-closed-unmerged PRs show AI-rejection language, treat as forbidden.
    """
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--state", "closed",
             "--limit", "30",
             "--json", "number,mergedAt,closedAt,comments"],
            capture_output=True, text=True, timeout=20
        )
        if result.returncode != 0:
            return False, ""
        prs = json.loads(result.stdout or "[]")
        for pr in prs:
            if pr.get("mergedAt"):
                continue
            for comment in (pr.get("comments") or []):
                body = (comment.get("body") or "").lower()
                if "ai content" in body or "ai-content" in body or "ai generated" in body or "ai-generated" in body:
                    if any(p in body for p in ["forbid", "policy", "not accept", "not permit", "prohibit", "reject"]):
                        return True, body[:200]
        return False, ""
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return False, ""


def check_repo_policy(repo, cache, scan_closed_history=True):
    """Return dict: {forbids_ai, ai_evidence, needs_cla, cla_evidence, has_contributing}."""
    if repo in cache:
        cached = cache[repo]
        if (
            not scan_closed_history
            or cached.get("forbids_ai")
            or cached.get("closed_history_checked")
        ):
            return cached
        forbids_ai, ai_ev = scan_closed_prs_for_ai_rejection(repo)
        cached["closed_history_checked"] = True
        cached["checked_at"] = datetime.now(timezone.utc).isoformat()
        if forbids_ai:
            cached["forbids_ai"] = True
            cached["ai_evidence"] = f"[from closed-PR history] {ai_ev}"
        cache[repo] = cached
        return cached

    contributing = (
        fetch_repo_file(repo, "CONTRIBUTING.md")
        or fetch_repo_file(repo, "CONTRIBUTING.rst")
        or fetch_repo_file(repo, ".github/CONTRIBUTING.md")
        or fetch_repo_file(repo, "docs/CONTRIBUTING.md")
        or ""
    )
    readme = fetch_repo_file(repo, "README.md") or ""
    combined = contributing + "\n" + readme

    forbids_ai, ai_ev = scan_ai_policy(combined)
    needs_cla, cla_ev = scan_cla_required(combined)

    # Secondary: check closed-PR rejection history for off-repo policies
    if not forbids_ai and scan_closed_history:
        forbids_ai, ai_ev = scan_closed_prs_for_ai_rejection(repo)
        if forbids_ai:
            ai_ev = f"[from closed-PR history] {ai_ev}"

    result = {
        "forbids_ai": forbids_ai,
        "ai_evidence": ai_ev,
        "needs_cla": needs_cla,
        "cla_evidence": cla_ev,
        "has_contributing": bool(contributing),
        "closed_history_checked": scan_closed_history,
        "checked_at": datetime.now(timezone.utc).isoformat(),
    }
    cache[repo] = result
    return result


def has_duplicate_pr(repo, issue_number):
    """True if an open PR already references this issue via Fixes/Closes/Resolves."""
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--state", "open",
             "--search", f"#{issue_number}",
             "--json", "number,title,author,body"],
            capture_output=True, text=True, timeout=15
        )
        if result.returncode != 0:
            return False
        prs = json.loads(result.stdout or "[]")
        keyword_re = re.compile(
            rf"\b(fixes|closes|resolves)\s+#{issue_number}\b",
            re.IGNORECASE,
        )
        for pr in prs:
            if keyword_re.search(pr.get("body") or "") or f"#{issue_number}" in (pr.get("title") or ""):
                return True
        return False
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return False


def _fetch_issue_comments(repo, issue_number):
    """Return list of {login, body, author_association} dicts, or []."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/issues/{issue_number}/comments",
             "--jq", "[.[] | {login: .user.login, body: .body, author_association: .author_association}]"],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode != 0:
            return []
        return json.loads(result.stdout or "[]")
    except (subprocess.TimeoutExpired, json.JSONDecodeError):
        return []


# Labels that block contribution — DETERMINISTIC match, stays in Python.
# For dispute / AI-policy / claim interpretation, see pr-direction-check skill.
BLOCK_LABELS = {
    "wontfix", "won't fix", "wont fix",
    "invalid", "duplicate",
    "needs-design", "needs design", "design needed",
    "needs-discussion", "needs discussion",
    "blocked", "on hold", "on-hold",
    "status: blocked", "status: on-hold",
    "question", "stale",
    "bounty", "onboarding", "community",
}


def has_block_label(issue):
    """True if issue carries a label that blocks contribution (wontfix, invalid, etc.).

    Deterministic label string match. Judgment calls (dispute detection,
    stale-but-still-valid) are deferred to pr-direction-check skill.
    """
    for lbl in issue.get("labels", []):
        name = (lbl.get("name") if isinstance(lbl, dict) else str(lbl)).strip().lower()
        if name in BLOCK_LABELS:
            return True, name
    return False, ""


def preflight_filter(issues, scan_closed_history=True):
    """Return (approved, rejected) tuples with reasons.

    ONLY DETERMINISTIC GATES run here. Judgment calls (dispute detection,
    AI-policy interpretation, claim-recency reading) are deferred to the
    pr-direction-check skill, invoked downstream by /github-pr Phase 2.5.

    Deterministic gates, in order:
      1. Issue has block-label (wontfix / invalid / needs-design / etc.)
      2. Duplicate open PR already references this issue (Fixes/Closes/Resolves #N)
      3. Repository policy explicitly forbids AI-generated contributions
      4. Contributing.md exists check (info only — the skill will READ it)

    Passing preflight means the issue is worth spending the claude -p session
    on; the session itself runs pr-direction-check for the nuanced verdict.
    """
    cache = load_policy_cache()
    approved = []
    rejected = []

    total = len(issues)
    for index, issue in enumerate(issues, 1):
        repo = issue["repository"]["nameWithOwner"]
        number = issue["number"]
        log(f"preflight {index}/{total}: {repo}#{number}")

        # Gate 1: block-label — deterministic
        blocked, lbl = has_block_label(issue)
        if blocked:
            rejected.append((issue, f"Issue has block-label '{lbl}'"))
            log(f"preflight rejected: {repo}#{number} block-label={lbl!r}")
            continue

        # Gate 2: duplicate open PR — deterministic `Fixes #N` grep
        if has_duplicate_pr(repo, number):
            rejected.append((issue, f"Open PR already references #{number}"))
            log(f"preflight rejected: {repo}#{number} duplicate open PR")
            continue

        # Gather the data the skill will judge — but don't judge here.
        # Cache fetched data on the issue so the prompt can pass it along.
        policy = check_repo_policy(
            repo,
            cache,
            scan_closed_history=scan_closed_history,
        )  # fetches CONTRIBUTING.md text
        if policy.get("forbids_ai"):
            evidence = (policy.get("ai_evidence") or "").replace("\n", " ")[:180]
            rejected.append((issue, f"Repository policy forbids AI contributions: {evidence}"))
            log(f"preflight rejected: {repo}#{number} AI contribution policy")
            continue

        comments = _fetch_issue_comments(repo, number)
        issue["_policy"] = policy
        issue["_comments"] = comments[-20:]  # last 20 for the skill
        approved.append(issue)
        log(f"preflight approved: {repo}#{number}")

    save_policy_cache(cache)
    return approved, rejected


def extract_pr_url(text):
    match = re.search(r'https://github\.com/[^\s)]+/pull/\d+', text)
    return match.group(0) if match else None


def write_status(status, detail="", extra=None):
    os.makedirs(os.path.dirname(STATUS_FILE), exist_ok=True)
    ts = datetime.now(timezone.utc).isoformat()
    payload = {"status": status, "detail": detail, "timestamp": ts}
    if extra:
        payload.update(extra)
    with open(STATUS_FILE, "w") as f:
        json.dump(payload, f)


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="discover and preflight candidate issues without invoking ClaudeCode",
    )
    ap.add_argument(
        "--issue-limit",
        type=int,
        default=12,
        help="number of discovered issues to preflight before handing off",
    )
    ap.add_argument(
        "--approved-limit",
        type=int,
        default=5,
        help="maximum approved candidates to include in the handoff",
    )
    ap.add_argument(
        "--languages",
        default=",".join(LANGUAGES),
        help="comma-separated GitHub search languages",
    )
    ap.add_argument(
        "--labels",
        default="good first issue,help wanted,bug",
        help="comma-separated GitHub issue labels to search",
    )
    ap.add_argument(
        "--per-query-limit",
        type=int,
        default=2,
        help="number of issues fetched per language/label query",
    )
    ap.add_argument(
        "--skip-closed-pr-history",
        action="store_true",
        help="skip expensive closed-PR AI-policy history scan; useful for first local smoke tests",
    )
    return ap.parse_args()


def split_csv(raw):
    return [part.strip() for part in raw.split(",") if part.strip()]


def main():
    args = parse_args()
    auth = gh_auth_status()
    if auth.returncode != 0:
        detail = (auth.stderr or auth.stdout or "").strip()
        write_status("github-auth-failed", detail)
        print(json.dumps({
            "wakeAgent": False,
            "status": "github-auth-failed",
            "detail": detail,
            "next": "Run `gh auth login -h github.com`, then retry the dry-run.",
        }, indent=2, ensure_ascii=False))
        return

    os.makedirs(WORKSPACE, exist_ok=True)
    os.makedirs(CONTRIB_ROOT, exist_ok=True)
    os.makedirs(PR_STAGE_ROOT, exist_ok=True)

    languages = split_csv(args.languages)
    labels = split_csv(args.labels)
    mode = "dry-run" if args.dry_run else "real run"
    log(f"start {mode}: languages={languages} labels={labels} per_query_limit={args.per_query_limit}")
    raw_issues = get_claimable_issues(
        languages=languages,
        labels=labels,
        per_query_limit=args.per_query_limit,
    )
    if not raw_issues:
        write_status("no-issues-found")
        print(json.dumps({"wakeAgent": False}))
        return

    issue_limit = max(1, args.issue_limit)
    approved_limit = max(1, args.approved_limit)
    log(f"preflight input: {min(len(raw_issues), issue_limit)} of {len(raw_issues)} discovered issue(s)")
    approved, rejected = preflight_filter(
        raw_issues[:issue_limit],
        scan_closed_history=not args.skip_closed_pr_history,
    )
    approved = approved[:approved_limit]

    if rejected:
        print("Preflight rejections:")
        for issue, reason in rejected:
            repo = issue["repository"]["nameWithOwner"]
            print(f"  - {repo}#{issue['number']}: {reason}")

    if not approved:
        detail = f"{len(rejected)} rejected in preflight, 0 approved"
        write_status("no-approved-issues", detail)
        print(json.dumps({"wakeAgent": False}))
        return

    issue_lines = []
    for issue in approved:
        repo = issue["repository"]["nameWithOwner"]
        pol = issue.get("_policy", {})
        flags = []
        if pol.get("needs_cla"):
            flags.append("CLA-REQUIRED")
        if not pol.get("has_contributing"):
            flags.append("NO-CONTRIBUTING")
        flag_str = f" [{', '.join(flags)}]" if flags else ""
        issue_lines.append(
            f"- {repo}#{issue['number']}: {issue['title']}{flag_str}"
        )
    issue_list = "\n".join(issue_lines)

    if args.dry_run:
        payload = {
            "wakeAgent": False,
            "dryRun": True,
            "rawIssueCount": len(raw_issues),
            "issueLimit": issue_limit,
            "approvedLimit": approved_limit,
            "languages": languages,
            "labels": labels,
            "perQueryLimit": max(1, args.per_query_limit),
            "approvedCount": len(approved),
            "rejectedCount": len(rejected),
            "approved": [
                {
                    "repo": issue["repository"]["nameWithOwner"],
                    "number": issue["number"],
                    "title": issue.get("title", ""),
                    "labels": [
                        (label.get("name") if isinstance(label, dict) else str(label))
                        for label in issue.get("labels", [])
                    ],
                    "policy": issue.get("_policy", {}),
                }
                for issue in approved
            ],
            "rejected": [
                {
                    "repo": issue["repository"]["nameWithOwner"],
                    "number": issue["number"],
                    "title": issue.get("title", ""),
                    "reason": reason,
                }
                for issue, reason in rejected
            ],
        }
        write_status(
            "dry-run",
            f"{len(approved)} approved, {len(rejected)} rejected",
            extra={
                "approved_count": len(approved),
                "rejected_count": len(rejected),
            },
        )
        print(json.dumps(payload, indent=2, ensure_ascii=False)[:6000])
        return

    # Build the direction-check input blob for each candidate — the skill
    # reads this to make the judgment call Python can't reliably make.
    issue_blobs = []
    for issue in approved:
        pol = issue.get("_policy", {})
        comments = issue.get("_comments", [])
        blob = {
            "repo": issue["repository"]["nameWithOwner"],
            "issue_number": issue["number"],
            "issue_title": issue.get("title", ""),
            "labels": [(l.get("name") if isinstance(l, dict) else str(l))
                       for l in issue.get("labels", [])],
            "last_comments": [
                {"author": c.get("login"),
                 "role": c.get("author_association"),
                 "body": (c.get("body") or "")[:1500]}
                for c in comments
            ],
            "contributing_md_present": pol.get("has_contributing", False),
            "needs_cla_signal": pol.get("needs_cla", False),
        }
        issue_blobs.append(blob)

    direction_blob_json = json.dumps(issue_blobs, ensure_ascii=False, indent=2)[:8000]

    prompt = (
        f"/github-pr\n\n"
        f"Candidate issues (preflight-approved — block-label + duplicate-PR gates passed):\n\n"
        f"{issue_list}\n\n"
        f"DIRECTION-CHECK INPUT (judgment data — consume via pr-direction-check skill):\n"
        f"```json\n{direction_blob_json}\n```\n\n"
        f"Routing anchors (must follow exactly):\n"
        f"- Workspace root: {WORKSPACE}\n"
        f"- Contribution repos: {CONTRIB_ROOT}/<repo-name>/\n"
        f"- Planning-with-Files root: {PR_STAGE_ROOT}/<repo-name>/\n"
        f"- Required files: task_plan.md, findings.md, progress.md\n"
        f"- PR report: {PR_STAGE_ROOT}/<repo-name>/pr-report.md\n\n"
        f"MANDATORY FIRST STEP — Phase 2.5 direction check:\n"
        f"For each candidate, invoke Skill(\"pr-direction-check\") with the matching\n"
        f"blob above. The skill returns DIRECTION_VERDICT: <status> | <reason>.\n"
        f"- proceed → continue to clone + code\n"
        f"- block:* → emit PIPELINE_RESULT with the matching status, skip this candidate\n"
        f"- yield:* → emit PIPELINE_RESULT: duplicate | <reason>, skip\n"
        f"- ambiguous:* → STOP, emit PIPELINE_RESULT: needs-human | <reason>, do NOT\n"
        f"  submit anything. Surface the ambiguity in the final report so a human decides.\n\n"
        f"FINAL-SUBMISSION GATES (re-check right before `gh pr create`):\n"
        f"1. Duplicate check — a PR may have opened in the last hour; if so, close your\n"
        f"   branch with a polite yield.\n"
        f"2. If CLA required and unsigned: emit PIPELINE_RESULT: cla-blocked.\n\n"
        f"REPLY / PR-BODY TONE (non-negotiable):\n"
        f"- Humility over cleverness. Use 'I might be wrong, but...',\n"
        f"  'If this direction doesn't fit, no problem.'\n"
        f"- No internal tooling references (agent names, orchestration, 'my analysis shows').\n"
        f"- Match the project's language. AI disclosure per PullRequest.md §AI Disclosure.\n"
        f"- No status tables, no bolded usernames, no emoji-headed sections.\n\n"
        f"Use codex:codex-rescue for implementation; gemini:gemini-consult for architecture.\n"
        f"Pick the most suitable proceed-verdict candidate and execute the full pipeline.\n\n"
        f"IMPORTANT: At the end, print in this exact format:\n"
        f"PIPELINE_RESULT: <status> | <pr_url_or_reason>\n"
        f"PIPELINE_QUALITY_SCORE: <float 0-10>   # mean of triple-review; required when status=pr-created\n\n"
        f"Status values: pr-created, pr-failed, issue-skipped, needs-human,\n"
        f"repo-forbids-ai, cla-blocked, duplicate, maintainer-disputed, error"
    )

    result = subprocess.run(
        [CONFIG.claude_bin, "-p", "--model", CONFIG.claude_model,
         "--dangerously-skip-permissions",
         "--max-budget-usd", CONFIG.claude_max_budget_usd,
         prompt],
        capture_output=True, text=True,
        timeout=7200,
        cwd=WORKSPACE
    )

    stdout = result.stdout.strip()
    stderr = result.stderr.strip()

    if result.returncode != 0:
        detail = stderr[:500] if stderr else "unknown error"
        write_status("error", f"exit {result.returncode}: {detail}")
        print(f"PIPELINE_ERROR: ClaudeCode exited {result.returncode}\n{detail}")
        return

    if not stdout:
        write_status("empty-output", f"exit 0 but no stdout. stderr: {stderr[:200]}")
        print(f"PIPELINE_ERROR: ClaudeCode exited 0 but produced no output.")
        if stderr:
            print(f"stderr: {stderr[:1000]}")
        print(f"\nCandidate issues were:\n{issue_list}")
        return

    pr_url = extract_pr_url(stdout)
    pipeline_match = re.search(r'PIPELINE_RESULT:\s*(\S+)\s*\|\s*(.*)', stdout)
    score_match = re.search(r'PIPELINE_QUALITY_SCORE:\s*([0-9]+(?:\.[0-9]+)?)', stdout)
    score = float(score_match.group(1)) if score_match else None

    QUALITY_THRESHOLD = CONFIG.github_pr_quality_threshold

    if pipeline_match:
        status = pipeline_match.group(1).strip()
        detail = pipeline_match.group(2).strip()

        # Quality-score enforcement: if status claims pr-created, require a
        # score ≥ threshold. Block the "success" classification otherwise.
        if status == "pr-created":
            if score is None:
                status = "pr-created-unscored"
                detail = f"SCORE MISSING — original detail: {detail}"
            elif score < QUALITY_THRESHOLD:
                status = "quality-blocked"
                detail = f"score={score} < {QUALITY_THRESHOLD} — original: {detail}"
            else:
                detail = f"{detail}  [quality={score}]"
        extra = {"quality_score": score} if score is not None else {}
        write_status(status, detail, extra=extra)
    elif pr_url:
        if score is None or score < QUALITY_THRESHOLD:
            write_status("pr-created-unscored" if score is None else "quality-blocked",
                         pr_url, extra={"quality_score": score} if score is not None else {})
        else:
            write_status("pr-created", pr_url, extra={"quality_score": score})
    else:
        write_status("completed-no-pr", stdout[-200:])

    print(stdout[-4000:] if len(stdout) > 4000 else stdout)


if __name__ == "__main__":
    main()
