#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

usage() {
  cat <<'EOF'
Usage: notebooklm_sidecar_sync.sh --source-file <path> --topic <slug> [options]

Options:
  --source-file <path>    Markdown source generated by research lane (required)
  --topic <slug>          Topic slug, used in output filename (required)
  --notebook-id <id>      NotebookLM notebook id (optional)
  --output-dir <dir>      Output dir (default: runtime/nlm)
  --dry-run               Skip NotebookLM remote write, only write local sidecar
EOF
}

SOURCE_FILE=""
TOPIC=""
NOTEBOOK_ID="${NLM_NOTEBOOK_ID:-}"
OUTPUT_DIR="${NLM_SIDECAR_OUTPUT_DIR:-$ROOT/runtime/nlm}"
DRY_RUN="${NLM_SIDECAR_DRY_RUN:-0}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-file)
      SOURCE_FILE="${2:-}"; shift 2 ;;
    --topic)
      TOPIC="${2:-}"; shift 2 ;;
    --notebook-id)
      NOTEBOOK_ID="${2:-}"; shift 2 ;;
    --output-dir)
      OUTPUT_DIR="${2:-}"; shift 2 ;;
    --dry-run)
      DRY_RUN=1; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "unknown arg: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "$SOURCE_FILE" || -z "$TOPIC" ]]; then
  echo "missing required args: --source-file and --topic" >&2
  usage
  exit 1
fi
if [[ ! -f "$SOURCE_FILE" ]]; then
  echo "source file not found: $SOURCE_FILE" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"
DATE_STR="$(date +%F)"
OUT_FILE="$OUTPUT_DIR/${DATE_STR}-${TOPIC}.md"

python3 - "$SOURCE_FILE" "$OUT_FILE" "$TOPIC" "$DATE_STR" <<'PY'
import re
import sys
from pathlib import Path

source_file, out_file, topic, date_str = sys.argv[1:5]
src = Path(source_file).read_text(encoding="utf-8")
words = re.findall(r"\S+", src)
abstract_words = words[:200]
abstract = " ".join(abstract_words).strip()

bullets = []
for line in src.splitlines():
    s = line.strip()
    if s.startswith("- ") or s.startswith("* "):
        bullets.append(s[2:].strip())
    if len(bullets) >= 5:
        break
if not bullets:
    sentences = re.split(r"[。！？.!?]\s*", src)
    for sent in sentences:
        sent = sent.strip()
        if sent:
            bullets.append(sent[:120])
        if len(bullets) >= 5:
            break

title = f"NLM Sidecar Digest · {topic} · {date_str}"
content = [
    f"# {title}",
    "",
    "## title",
    topic,
    "",
    "## abstract",
    abstract or "(empty)",
    "",
    "## key_findings",
]
for b in bullets[:5]:
    content.append(f"- {b}")
content.extend(
    [
        "",
        "## relevance_to_beatless",
        "- 可作为 Lacia heartbeat 的候选摘要输入（建议 <=500 token）。",
        "- 保留 sidecar 隔离，不直接污染主上下文。",
        "",
        "## source_file",
        source_file,
    ]
)
Path(out_file).write_text("\n".join(content) + "\n", encoding="utf-8")
PY

SYNC_STATUS="local_only"
NLM_NOTE_ID=""
NLM_ERROR=""

if [[ "$DRY_RUN" -eq 0 && -n "$NOTEBOOK_ID" ]]; then
  if command -v nlm >/dev/null 2>&1; then
    CONTENT="$(cat "$OUT_FILE")"
    set +e
    NLM_OUT="$(nlm note create "$NOTEBOOK_ID" --title "Sidecar ${TOPIC} ${DATE_STR}" --content "$CONTENT" 2>&1)"
    NLM_RC=$?
    set -e
    if [[ "$NLM_RC" -eq 0 ]]; then
      SYNC_STATUS="synced"
      NLM_NOTE_ID="$(echo "$NLM_OUT" | sed -n 's/.*"note_id":[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
    else
      SYNC_STATUS="failed"
      NLM_ERROR="$NLM_OUT"
    fi
  else
    SYNC_STATUS="failed"
    NLM_ERROR="nlm command not found"
  fi
fi

python3 - "$OUT_FILE" "$SYNC_STATUS" "$TOPIC" "$NOTEBOOK_ID" "$NLM_NOTE_ID" "$NLM_ERROR" "$OUTPUT_DIR/last_sync.json" <<'PY'
import json
import sys
from pathlib import Path

out_file, status, topic, notebook_id, note_id, err, sink = sys.argv[1:8]
payload = {
    "topic": topic,
    "sidecar_file": out_file,
    "sync_status": status,
    "notebook_id": notebook_id or None,
    "note_id": note_id or None,
    "error": err or None,
}
Path(sink).write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(json.dumps(payload, ensure_ascii=False))
PY
