#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="/home/yarizakurahime/claw/Beatless"
OPENCLAW_HOME="/home/yarizakurahime/.openclaw"
CONFIG_FILE="${OPENCLAW_HOME}/openclaw.json"
BACKUP_FILE="${OPENCLAW_HOME}/openclaw.json.bak.beatless.$(date +%Y%m%d-%H%M%S)"
SKILLS_SRC="/home/yarizakurahime/claw/openclaw/skills"
SHARED_DIR="${OPENCLAW_HOME}/beatless"
AUTH_SOURCE_PRIMARY="${OPENCLAW_HOME}/agents/taizi/agent/auth-profiles.json"
AUTH_SOURCE_FALLBACK="${OPENCLAW_HOME}/agents/main/agent/auth-profiles.json"

WORKSPACE_LACIA="${OPENCLAW_HOME}/workspace-lacia"
WORKSPACE_METHODE="${OPENCLAW_HOME}/workspace-methode"
WORKSPACE_CODEX="${OPENCLAW_HOME}/workspace-codex-builder"
WORKSPACE_GEMINI="${OPENCLAW_HOME}/workspace-gemini-researcher"
WORKSPACE_CLAUDE="${OPENCLAW_HOME}/workspace-claude-architect"

SKILLS=(
  "coding-agent"
  "gemini"
  "github"
  "gh-issues"
  "session-logs"
  "healthcheck"
  "tmux"
)

ensure_workspace() {
  local ws="$1"
  mkdir -p "${ws}/skills"
}

sync_auth_profiles() {
  local ws_agent="$1"
  local target="${OPENCLAW_HOME}/agents/${ws_agent}/agent/auth-profiles.json"
  mkdir -p "$(dirname "${target}")"
  if [[ -f "${AUTH_SOURCE_PRIMARY}" ]]; then
    cp "${AUTH_SOURCE_PRIMARY}" "${target}"
  elif [[ -f "${AUTH_SOURCE_FALLBACK}" ]]; then
    cp "${AUTH_SOURCE_FALLBACK}" "${target}"
  fi
}

install_skills() {
  local ws="$1"
  local skill
  for skill in "${SKILLS[@]}"; do
    if [[ -d "${SKILLS_SRC}/${skill}" ]]; then
      rm -rf "${ws}/skills/${skill}"
      cp -R "${SKILLS_SRC}/${skill}" "${ws}/skills/${skill}"
    fi
  done
}

write_common_files() {
  local ws="$1"
  local role="$2"
  local owner="$3"
  cat > "${ws}/AGENTS.md" <<EOF
# ${role}

## Mission
- Run as ${owner} in the Beatless architecture.
- Use ${SHARED_DIR}/TASKS.yaml as the single source of truth.
- Never invent task status; write explicit DONE/DOING/BLOCKED/NEXT updates.

## Execution Rules
- Before starting work: read ${SHARED_DIR}/TASKS.yaml and claim one READY task.
- While working: only update files under the assigned task scope.
- After work: write quality checks and next action back to task ledger.
- For uncertain or risky operations: mark BLOCKED with concrete reason.

## Memory and Session
- Persist durable decisions in ${SHARED_DIR}/MEMORY.md.
- Keep heartbeat actions short; avoid long execution in heartbeat runs.
- Use cron/isolated runs for heavy jobs, heartbeat for dispatch and health checks.
EOF

  cat > "${ws}/TOOLS.md" <<EOF
# Tools

- Prefer local file operations and explicit task-ledger updates.
- Use coding and verification tools only within assigned task boundaries.
- Keep logs in ${SHARED_DIR}/logs.
EOF
}

write_role_files() {
  cat > "${WORKSPACE_LACIA}/HEARTBEAT.md" <<EOF
# Lacia Heartbeat

0. Check ${SHARED_DIR}/pending-delivery.json
   - If pending summaries exist, replay one summary and mark delivered.
1. Read ${SHARED_DIR}/TASKS.yaml
2. If no READY tasks, return HEARTBEAT_OK
3. Promote one BACKLOG task to READY if capacity allows
4. Dispatch to methode or reviewer flow
5. Emit concise status summary
EOF

  cat > "${WORKSPACE_METHODE}/HEARTBEAT.md" <<EOF
# Methode Heartbeat

1. Read ${SHARED_DIR}/TASKS.yaml
2. Claim one READY task assigned to methode
3. Execute implementation
4. Move task to REVIEW with artifact list
EOF
}

write_shared_files() {
  mkdir -p "${SHARED_DIR}/logs"
  cat > "${SHARED_DIR}/TASKS.yaml" <<EOF
meta:
  schema_version: 1
  updated_at: "$(date -Iseconds)"
  owner: "beatless"

tasks:
  - id: "BT-001"
    title: "Bootstrap Beatless architecture"
    type: "system_setup"
    priority: "high"
    status: "ready"
    assigned_agent: "methode"
    context_hash: "beatless-bootstrap-001"
    acceptance_criteria:
      - "Gateway routes to lacia"
      - "Beatless workspaces and skills installed"
      - "Edict agents disabled from active routing"
    notes: "Auto-generated by setup script"
EOF

  cat > "${SHARED_DIR}/QUALITY_GATES.md" <<EOF
# Beatless Quality Gates

- All changed config must be parseable JSON/YAML.
- Every task update must include DONE/DOING/BLOCKED/NEXT.
- No direct destructive commands without explicit operator confirmation.
- Keep changes reversible; preserve backup before overwrite.
EOF

  cat > "${SHARED_DIR}/MEMORY.md" <<EOF
# Beatless Memory

- Architecture: planner(lacia) -> executor(methode) + experts(codex/gemini/claude)
- Mode labels: emergency(Kouka strategy), explore(Snowdrop strategy), review(Satonus strategy)
- Entry binding: feishu -> lacia
- Helper ACP agents: codex-builder, gemini-researcher, claude-architect
EOF

  cat > "${SHARED_DIR}/pending-delivery.json" <<EOF
{
  "version": 1,
  "items": []
}
EOF

  cat > "${SHARED_DIR}/DELIVERY.md" <<EOF
# Delivery Fallback Protocol

1. Every final conclusion must be persisted to:
   - /home/yarizakurahime/claw/Report/final-summary-YYYYMMDD-HHMMSS.md
2. Track unsent summaries in:
   - ${SHARED_DIR}/pending-delivery.json
3. Lacia heartbeat attempts replay of pending items.
4. On successful replay, mark delivered with timestamp.
EOF
}

patch_openclaw_config() {
  cp "${CONFIG_FILE}" "${BACKUP_FILE}"

  jq \
    --arg ws_lacia "${WORKSPACE_LACIA}" \
    --arg ws_methode "${WORKSPACE_METHODE}" \
    --arg ws_codex "${WORKSPACE_CODEX}" \
    --arg ws_gemini "${WORKSPACE_GEMINI}" \
    --arg ws_claude "${WORKSPACE_CLAUDE}" \
    '
      .agents.list = [
        {
          id: "lacia",
          name: "Lacia",
          workspace: $ws_lacia,
          model: { primary: "kimi-coding/k2p5", fallbacks: [] },
          subagents: { allowAgents: ["methode","codex-builder","gemini-researcher","claude-architect"] }
        },
        {
          id: "methode",
          name: "Methode",
          workspace: $ws_methode,
          model: { primary: "kimi-coding/k2p5", fallbacks: [] },
          subagents: { allowAgents: ["lacia","codex-builder","gemini-researcher","claude-architect"] }
        },
        {
          id: "codex-builder",
          name: "Codex构建者",
          workspace: $ws_codex,
          model: { primary: "kimi-coding/k2p5", fallbacks: [] },
          subagents: { allowAgents: ["lacia","methode"] },
          runtime: { type: "acp", acp: { agent: "codex", backend: "acpx", mode: "persistent", cwd: "/home/yarizakurahime/claw" } }
        },
        {
          id: "gemini-researcher",
          name: "Gemini研究员",
          workspace: $ws_gemini,
          model: { primary: "kimi-coding/k2p5", fallbacks: [] },
          subagents: { allowAgents: ["lacia","methode"] },
          runtime: { type: "acp", acp: { agent: "gemini", backend: "acpx", mode: "persistent", cwd: "/home/yarizakurahime/claw" } }
        },
        {
          id: "claude-architect",
          name: "Claude架构师",
          workspace: $ws_claude,
          model: { primary: "kimi-coding/k2p5", fallbacks: [] },
          subagents: { allowAgents: ["lacia","methode"] },
          runtime: { type: "acp", acp: { agent: "claude", backend: "acpx", mode: "persistent", cwd: "/home/yarizakurahime/claw" } }
        }
      ]
      | .bindings = ((.bindings // []) | map(select(.match.channel != "feishu")))
      | .bindings += [
          {
            agentId: "lacia",
            comment: "Beatless entrypoint for Feishu",
            match: { channel: "feishu" }
          }
        ]
    ' "${CONFIG_FILE}" > "${CONFIG_FILE}.tmp"

  mv "${CONFIG_FILE}.tmp" "${CONFIG_FILE}"
}

install_souls() {
  cp "${BASE_DIR}/souls/005-lacia/SOUL.md" "${WORKSPACE_LACIA}/SOUL.md"
  cp "${BASE_DIR}/souls/004-methode/SOUL.md" "${WORKSPACE_METHODE}/SOUL.md"
}

main() {
  ensure_workspace "${WORKSPACE_LACIA}"
  ensure_workspace "${WORKSPACE_METHODE}"
  ensure_workspace "${WORKSPACE_CODEX}"
  ensure_workspace "${WORKSPACE_GEMINI}"
  ensure_workspace "${WORKSPACE_CLAUDE}"

  write_common_files "${WORKSPACE_LACIA}" "Lacia" "planner"
  write_common_files "${WORKSPACE_METHODE}" "Methode" "executor"
  write_role_files
  write_shared_files
  install_souls

  install_skills "${WORKSPACE_LACIA}"
  install_skills "${WORKSPACE_METHODE}"
  install_skills "${WORKSPACE_CODEX}"
  install_skills "${WORKSPACE_GEMINI}"
  install_skills "${WORKSPACE_CLAUDE}"

  sync_auth_profiles "lacia"
  sync_auth_profiles "methode"

  patch_openclaw_config

  echo "Beatless setup complete."
  echo "Backup config: ${BACKUP_FILE}"
  echo "Patched config: ${CONFIG_FILE}"
}

main "$@"
